version: '3.2'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/proxy.conf
      - nginx-config:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certificates:/etc/nginx/certs:ro

  dockergen:
    container_name: dockergen
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  letsencryptit:
    container_name: letsencryptit
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    restart: always
    userns_mode: host
    volumes:
      - nginx-config:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certificates:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginxproxy
      - NGINX_DOCKER_GEN_CONTAINER=nginxproxy-dockergen
    
volumes:
  nginx-config:
  nginx-vhost:
  nginx-html:
  nginx-certificates:

